/**
 * Seed tag lists for review cuisines and food types.
 * Used by the post-review form tag pickers (client-side only).
 */

export const CUISINE_TAGS_SEED = [
  'Arabic',
  'Middle Eastern',
  'Lebanese',
  'Syrian',
  'Turkish',
  'Greek',
  'Persian (Iranian)',
  'Indian',
  'Pakistani',
  'Chinese',
  'Thai',
  'Vietnamese',
  'Japanese',
  'Korean',
  'Italian',
  'French',
  'Spanish',
  'Mexican',
  'Brazilian',
  'Peruvian',
  'American',
  'Mediterranean',
  'Seafood',
  'Steakhouse',
  'Vegetarian',
  'Vegan',
  'International',
  'Fusion',
] as const;

export const FOOD_TYPE_TAGS_SEED = [
  'Burgers',
  'Pizza',
  'Sushi',
  'Ramen',
  'Pho',
  'Tacos',
  'Kebabs',
  'Shawarma',
  'Falafel',
  'Grill (BBQ/Charcoal)',
  'Steak',
  'Seafood',
  'Pasta',
  'Curry',
  'Biryani',
  'Dumplings',
  'Fried Chicken',
  'Sandwiches',
  'Salads',
  'Wraps',
  'Desserts',
  'Ice Cream',
  'Bakeries',
  'Coffee & Tea',
  'Smoothies & Juices',
  'Breakfast',
  'Brunch',
] as const;

