[build]
  command = "npm run build"
  publish = "dist/food-blog/browser"

[build.environment]
  NODE_VERSION = "24"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
